### PR TITLE
Register buttons

### PR DESCRIPTION
**Pull request by ilmartyrk**
Register toolbar button to add button from config

### CODE REVIEW

**Comment by JohnMcLear** [comment]
This is way too messy to merge dude, can you tidy it up please?

**Comment by ilmartyrk** [comment]
@JohnMcLear fixed all conflicts, also added a check to index.js  `exports.eejsBlock_editbarMenuLeft` to ignore the default button if button is defined in settings.json under toolbar config

**Comment by JohnMcLear** [comment]
@ilmartyrk it' still showing conficts??? :)

**Comment by ilmartyrk** [comment]
@JohnMcLear, should be fixed now, I merged the ether/ep_comments master and resolved the conflicts

**Comment by JohnMcLear** [comment]
Please check this with the file menu plugin, it looks like you deleted the ejs that is used by the file menu plugin?

**Comment by ilmartyrk** [comment]
Oh, ok, sorry about that, I've never used that plugin before, I saw that there were two places where a button was added to the toolbar, as one seemed deprecated and I didn't see any reference to this  `dd_insert` block in the documentation too, I removed it, I'll put it back.

**Comment by JohnMcLear** [comment]
No biggy, it's prolly rarely used but best to leave support in :)

**Pull request merged**
