### PR TITLE
Disable editing others comments

### PR DESCRIPTION
**Pull request by ilmartyrk**
Simple fix to https://github.com/ether/ep_comments/issues/125 with test

### CODE REVIEW

**Comment by JohnMcLear** [comment]
@rhansen afaik you were involved in the conversation.  Are we okay with the UX of this proposed fix?

**Comment by ilmartyrk** [comment]
@rhansen @JohnMcLear, I went a little further don't merge yet, will also disable deleting and will hide action buttons from UI for others comments

**Comment by ilmartyrk** [comment]
@rhansen @JohnMcLear now disabled deleting too and hide/remove action buttons from other users comments and replies, also added tests

**Comment by JohnMcLear** [comment]
Please flag as draft until it's ready for me to test/merge, thanks!

**Comment by ilmartyrk** [comment]
@JohnMcLear it's ready

**Comment by JohnMcLear** [comment]
Do the frontend tests pas for you?

http://loadtest:9001/tests/frontend/index.html?grep=ep_comments_page%20-%20Comment%20Delete%20when%20user%20presses%20the%20delete%20button%20on%20other%20users%20comment 

errors for me

**Comment by JohnMcLear** [comment]
btw if you work on the ether:ep_comments repo the tests will auto-run, you should have the sauce labs user/pass, lemme know if not.

**Comment by JohnMcLear** [comment]
I also experience

``Gritter Error: You must supply "text" parameter. 
Object { title: "Error", text: null, sticky: true, class_name: "error" }``

**Comment by JohnMcLear** [comment]
I experience quite a lot of frontend test failure, it could be something with my environment but I am not sure..  It would be helpful if you can pull your branch over to the ether/ep_comments repo and let sauce labs run the tests.  Also if you can look at the empty gritter msg that would be useful.

**Comment by ilmartyrk** [comment]
@JohnMcLear all tests pass on my machine, but I've noticed some race-condition kind of failures sometimes.  I've also noticed this gritter error thing. And I have no sauce labs user/pass.

**Comment by JohnMcLear** [comment]
test passes in chrome, fails in FF.

**Comment by edsaperia** [comment]
Editing someone else's comments is unintuitive, for sure, but I kind of understand why you'd make them that way - to keep the feeling of everything being collaborative and fluid.

As an alternative to fully signed & owned comments as being developed here, we could have "notes"; instead of a comment being a set of linear posts, it could be a little collaborative scratchpad that anyone can edit.

**Comment by ilmartyrk** [comment]
@JohnMcLear passing on chrome and FF, I am using Ubuntu 18, Chrome Version 86.0.4240.193 (Official Build) (64-bit) and Firefox 82.0.2 64-bit

**Comment by JohnMcLear** [comment]
Peep errors in travis logs.

**Comment by JohnMcLear** [comment]
@ilmartyrk dude plz fix tests!  Tnx

**Pull request merged**
