### PR TITLE
Css refactor, and more...

### PR DESCRIPTION
**Pull request by seballot**
I first start to fix the positioning of different element to suit new flex layout of etherpad core

But I ended doing quite some changes
- Simplify the template (less classes, use sub templates)
- Improve UX 
  - add message when click new comment without text select
  - Add button to reply or cancel when entering the reply input
  - allow to create comment with only suggested change
- commentIcons: hide the comment boxes, and use modals to display the comments when clicking the icon, so we save horizontal space
- Improve french translations
- fix comment position when there is padding on containers

And same for my PR on etherpad core, I din't get into fixing test, I'm sorry...

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Afaik ep_comments has test coverage, did you run the tests?

**Comment by seballot** [comment]
yes there are quite lot of specs ! nop I did not even run them, too afraid to see everything red :/

**Comment by JohnMcLear** [comment]
@seballot Run them, they should be okay 🍡

**Comment by seballot** [comment]
ah ah, it just crash at the beginning

image

**Comment by JohnMcLear** [comment]
Did it do that before you made any changes?

**Comment by seballot** [comment]
yes indeed, with etherpad develop branch and ep_comment on master, same error running specs

**Comment by JohnMcLear** [comment]
Ignore the error then, I will deal with it.

**Comment by seballot** [comment]
thanks !

**Pull request merged**
