### PR TITLE
Replace timeformat with momen tjs

### PR DESCRIPTION
**Pull request by ilmartyrk**
Moment js has allready the functionality of timeformat.js script, but it includes many more languages without the need to add new translation keys to language files.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Feel free to merge your own work but be mindful that tests must pass.  Afaik this was heavily test covered before 👍

**Comment by JohnMcLear** [comment]
@ilmartyrk is it still worth getting this sorted and merged in?  Feels like it going stale is not cool ;(

**Comment by ilmartyrk** [comment]
I will fix the tests and see that everything is working :)

**Comment by ilmartyrk** [comment]
@JohnMcLear fixed this pull too, I believe that using moment-js is better from localization point of view, it already has great coverage for different languages. I will soon add another pull that updates translation key and html layout a little, this was suggested from our head of localization as it makes the "change text from to" text more localizable

**Comment by JohnMcLear** [comment]
This branch cannot be rebased due to conflicts

**Pull request merged**
